

# POST http://localhost:3000/events/tapIn/10 HTTP/1.1
# content-type: application/json

# {
#     "categoryId": "sample"
# }

POST http://localhost:3000/events/tapOut/43 HTTP/1.1
# content-type: application/json

# {
#     "categoryId": "sample"
# }